theme = "ttox-mono"

[editor]
rulers = [100]
line-number = "relative"
auto-pairs = false
popup-border = "all" # needed to the current ttox theme
jump-label-alphabet = "jklfdshga√∏"

[editor.file-picker]
hidden = false

[keys.normal]
"=" = ":fmt"
" " = { w = ":reflow" } # Reflow text
"minus" = "flip_selections"

[keys.insert]
j = { k = "normal_mode" }
