theme = "ttox"

[editor]
rulers = [100]
line-number = "relative"
auto-pairs = false
popup-border = "all" # needed to the current ttox theme
jump-label-alphabet = "jklfdshga√∏"

[editor.file-picker]
hidden = false

[keys.normal]
"=" = ":fmt"

[keys.insert]
"j" = { k = "normal_mode" }
