theme = "ttox-mono"

[editor]
rulers = [100]
line-number = "relative"
auto-pairs = false
popup-border = "all"     # needed to the current ttox theme
end-of-line-diagnostics = "disable"

[editor.inline-diagnostics]
cursor-line = "disable"

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ["diff", "diagnostics", "spacer"]

[editor.whitespace.render]
nbsp = "all"
nnbsp = "all"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[keys.normal]
"=" = ":fmt"
"-" = "flip_selections"
V = "copy_selection_on_prev_line"
"ø" = "repeat_last_motion"
C-f = "@*<space>/<ret>"

[keys.normal." "]
w = ":reflow"
o = ":pipe sort"

[keys.insert]
j = { k = "normal_mode" }
J = { K = "normal_mode" }
